# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcommun', models.CharField(max_length=140)),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
